import {
  ChartNoAxesCombined,
  Crown,
  FileText,
  ReceiptText,
  ShieldCheck,
  Wallet,
} from "lucide-react";

const reportTemplates = [
  {
    title: "Complete CFO Report",
    description:
      "Consolidated sales, inventory, accounting, cash flow, tax, and risk analysis.",
    agent: "Report Writer Agent",
    icon: FileText,
    iconStyle: "bg-primary-soft text-primary",
    recommended: true,
  },
  {
    title: "Executive Brief",
    description:
      "Financial priorities, verified risks, and recommended next actions.",
    agent: "CEO Agent",
    icon: Crown,
    iconStyle: "bg-warning-soft text-warning",
    recommended: false,
  },
  {
    title: "Sales Performance",
    description:
      "Completed revenue, units sold, sales statuses, and top products.",
    agent: "Sales Agent",
    icon: ChartNoAxesCombined,
    iconStyle: "bg-success-soft text-success",
    recommended: false,
  },
  {
    title: "Cash Flow Summary",
    description:
      "Tracked inflows, recorded outflows, net movement, and expected inflows.",
    agent: "Cash Flow Agent",
    icon: Wallet,
    iconStyle: "bg-primary-soft text-primary",
    recommended: false,
  },
  {
    title: "Tax Summary",
    description:
      "Invoiced VAT grouped by invoice status with data-availability notes.",
    agent: "Tax Agent",
    icon: ReceiptText,
    iconStyle: "bg-warning-soft text-warning",
    recommended: false,
  },
  {
    title: "Risk Review",
    description:
      "Flagged expenses and duplicate candidates requiring human review.",
    agent: "Fraud Agent",
    icon: ShieldCheck,
    iconStyle: "bg-danger-soft text-danger",
    recommended: false,
  },
];

export default function ReportTemplates() {
  return (
    <section>
      <div className="mb-5">
        <h2 className="text-lg font-semibold text-text-primary">
          Report templates
        </h2>

        <p className="mt-1 text-sm text-text-secondary">
          Choose the financial analysis you want the AI agents to prepare.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 2xl:grid-cols-3">
        {reportTemplates.map((report) => {
          const Icon = report.icon;

          return (
            <article
              key={report.title}
              className="flex min-h-64 flex-col rounded-2xl border border-border bg-surface p-5 shadow-sm transition-shadow hover:shadow-md"
            >
              <div className="flex items-start justify-between gap-3">
                <span
                  className={`flex size-11 items-center justify-center rounded-xl ${report.iconStyle}`}
                >
                  <Icon size={21} strokeWidth={1.8} />
                </span>

                {report.recommended ? (
                  <span className="rounded-full bg-primary-soft px-2.5 py-1 text-xs font-medium text-primary">
                    Recommended
                  </span>
                ) : null}
              </div>

              <h3 className="mt-5 text-base font-semibold text-text-primary">
                {report.title}
              </h3>

              <p className="mt-2 flex-1 text-sm leading-6 text-text-secondary">
                {report.description}
              </p>

              <div className="mt-5 border-t border-border pt-4">
                <div className="mb-3 flex items-center justify-between gap-3">
                  <span className="text-xs text-text-secondary">
                    Generated by
                  </span>

                  <span className="text-xs font-medium text-text-primary">
                    {report.agent}
                  </span>
                </div>

                <button
                  type="button"
                  className="w-full rounded-xl border border-primary bg-primary-soft px-4 py-2.5 text-sm font-medium text-primary transition-colors hover:bg-primary hover:text-white"
                >
                  Generate report
                </button>
              </div>
            </article>
          );
        })}
      </div>

      <p className="mt-4 text-xs leading-5 text-text-secondary">
        Report generation buttons are design-only. PDF creation and report
        storage will be connected after the frontend design is complete.
      </p>
    </section>
  );
}